### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeffreymelvin-wf**

### CODE REVIEW

**Comment by infosec-wf** [comment]
## Raven
Number of Findings: 1
* Watched file ```README.md``` modified

The finding(s) listed above require security review.

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by infosec-wf** [comment]
## Raven
Number of Findings: 0

**Comment by jeffreymelvin-wf** [comment]
@tweek

**Comment by brettweiss-wf** [comment]
## Srcclr
SourceClear Results:
High Vulnerabilities: 0
Medium Vulnerabilities: 0
Low Vulnerabilities: 0
Score: 0

**Comment by jeffreymelvin-wf** [comment]
@tweek

**Comment by jeffreymelvin-wf** [comment]
@tweek

**Comment by jeffreymelvin-wf** [comment]
@tweek

**Comment by jeffreymelvin-wf** [comment]
@tweek

**Comment by jeffreymelvin-wf** [comment]
@tweek

**Comment by jeffreymelvin-wf** [comment]
@tweek

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by mairaemperley-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

The finding(s) listed above require security review.

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by mairaemperley-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

The finding(s) listed above require security review.

**Comment by infosec-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

As a result of the finding(s) listed above,a security review is required for this pull request.

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by brettweiss-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

As a result of the finding(s) listed above,a security review is required for this pull request.

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by brettweiss-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by jeffreymelvin-wf** [comment]
@aviary-wf

**Comment by jeffreymelvin-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by jeffreymelvin-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by jeffreymelvin-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by jeffreymelvin-wf** [comment]
## Raven
Number of Findings: 1
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8', '10'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by jeffreymelvin-wf** [comment]
## Raven

Number of Findings: 2
- Watched file `test.py` added
- Watched keyword `verify=False` in `README.md` line(s) ['8', '10'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by mairaemperley-wf** [comment]
## Raven
Number of Findings: 2
* Watched file ```test.py``` added
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8', '10'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

## Shrike
Shrike Scan Results:
Very High Vulnerabilities: 0
High Vulnerabilities: 0
Moderate Vulnerabilities: 0
Low Vulnerabilities: 0
Very Low Vulnerabilities: 0
Total Score: 0

**Comment by mairaemperley-wf** [comment]
## Raven
Number of Findings: 2
* Watched file ```test.py``` added
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8', '10'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

## Shrike
Shrike Scan Results:
Very High Vulnerabilities: 0
High Vulnerabilities: 1
Moderate Vulnerabilities: 1
Low Vulnerabilities: 0
Very Low Vulnerabilities: 0
Total Score: 70
See InfoSec Team for Details

**Comment by mairaemperley-wf** [comment]
## Shrike
Shrike Scan Results:
Very High Vulnerabilities: 0
High Vulnerabilities: 1
Moderate Vulnerabilities: 1
Low Vulnerabilities: 0
Very Low Vulnerabilities: 0
Total Score: 70
See InfoSec Team for Details

**Comment by mairaemperley-wf** [comment]
## Raven
Number of Findings: 2
* Watched file ```test.py``` added
* Watched keyword ```verify=False``` in ```README.md``` line(s) ['8', '10'] added

As a result of the finding(s) listed above, a security review is required for this pull request.

## Shrike
Shrike Scan Results:
Very High Vulnerabilities: 0
High Vulnerabilities: 1
Moderate Vulnerabilities: 1
Low Vulnerabilities: 0
Very Low Vulnerabilities: 0
Total Score: 70
See InfoSec Team for Details

**Pull request closed without merging**
